# Generated by Django 4.1.3 on 2022-11-27 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('type', models.CharField(choices=[('SHORT_ANSWER', 'Short answer'), ('PARAGRAPH', 'Paragraph answer'), ('RADIO', 'Radio options'), ('CHECKBOXES', 'Checkboxes'), ('DROPDOWN', 'Dropdown list')], default=('SHORT_ANSWER', 'Short answer'), max_length=32)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(null=True)),
                ('link', models.URLField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isShortAnswer', models.BooleanField(default=False)),
                ('short_answer_content', models.CharField(max_length=400)),
                ('isParagraph', models.BooleanField(default=False)),
                ('paragraph_content', models.CharField(max_length=3000)),
                ('isRadio', models.BooleanField(default=False)),
                ('radio_content', models.JSONField(default=dict, verbose_name='RadioData')),
                ('isCheckbox', models.BooleanField(default=False)),
                ('checkbox_content', models.JSONField(default=dict, verbose_name='CheckboxData')),
                ('isDropdown', models.BooleanField(default=False)),
                ('dropdown_content', models.CharField(max_length=1200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'),
        ),
    ]
