# Generated by Django 4.1.3 on 2022-12-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=dict, null=True, verbose_name='OptionData'),
        ),
    ]
