# Generated by Django 4.1.3 on 2022-12-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=dict, verbose_name='OptionData'),
        ),
    ]
