# Generated by Django 4.1.3 on 2022-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_remove_answer_question_item_answer_question_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="short_answer_content",
            new_name="question",
        ),
        migrations.RemoveField(
            model_name="question",
            name="checkbox_content",
        ),
        migrations.RemoveField(
            model_name="question",
            name="dropdown_content",
        ),
        migrations.RemoveField(
            model_name="question",
            name="paragraph_content",
        ),
        migrations.RemoveField(
            model_name="question",
            name="radio_content",
        ),
        migrations.RemoveField(
            model_name="question",
            name="title",
        ),
        migrations.AddField(
            model_name="question",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(default=dict, verbose_name="OptionData"),
        ),
    ]
