# Generated by Django 4.1.3 on 2022-12-09 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_alter_question_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="user",
        ),
        migrations.AlterField(
            model_name="survey",
            name="link",
            field=models.CharField(
                blank=True, default=uuid.uuid4, max_length=100, unique=True
            ),
        ),
    ]
