# Generated by Django 4.1.3 on 2022-12-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0004_remove_answer_user_alter_survey_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="choice",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="answer",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
